# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-10 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20210810_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='is_md',
            field=models.BooleanField(default=False, verbose_name='markdown语法'),
        ),
    ]
