# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-10 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_sidebar_is_md'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebar',
            name='is_md',
        ),
    ]
