# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-07 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_nave',
            new_name='is_nav',
        ),
    ]
